version: "1"
services:
- type: web
  name: fastapi-app
  env: python
  buildCommand: pip install -r requirements.txt
  startCommand: uvicorn app.main:app --host 0.0.0.0 --port 8000
  region: oregon

- type: web
  name: nodejs-service
  runtime: node
  repo: https://github.com/Belalaskaik/CandleVision-
  plan: starter
  envVars:
  - key: PUPPETEER_SKIP_DOWNLOAD
    sync: false
  - key: NODE_ENV
    sync: false
  region: oregon
  buildCommand: |
    apt-get update &&
    apt-get install -y chromium-browser &&
    npm install
  startCommand: node capture.js
