services:
  - type: web
    name: fastapi-app
    env: python
    buildCommand: |
      pip install --no-cache-dir -r requirements.txt
      echo "Checking FastAPI installation..."
      pip list | grep fastapi
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 10000
    dockerfilePath: './Dockerfile'
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"

  - type: web
    name: nodejs-service
    env: node
    buildCommand: npm install
    startCommand: node capture.js
    dockerfilePath: './Dockerfile'
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_SKIP_DOWNLOAD
        value: "true"

