# Exported from Render on 2024-05-09T06:02:55Z
services:
- type: web
  name: nodejs-service
  runtime: node
  repo: https://github.com/Belalaskaik/CandleVision-
  plan: starter
  envVars:
  - key: PUPPETEER_SKIP_DOWNLOAD
    sync: false
  - key: NODE_ENV
    sync: false
  region: oregon
  buildCommand: npm install
  startCommand: node capture.js
version: "1"
